apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.api.service_name }}
spec:
  type: LoadBalancer
  selector:
    app: {{ .Values.api.app_name }}
  ports:
    - name: api-http
      protocol: TCP
      port: {{ .Values.api.port }}
      targetPort: {{ .Values.api.port }}
    - name: mongo-express-http
      protocol: TCP
      port: {{ .Values.mongo_express.port }}
      targetPort: {{ .Values.mongo_express.port }}
