apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.api.service_name }}
  namespace: {{ .Values.namespace }}
spec:
  selector:
    app: {{ .Values.api.app_name }}
  ports:
  - protocol: TCP
    port: {{ .Values.api.port }}
    targetPort: {{ .Values.api.port }}
