###########################################################################
##
##  RestartR
##  
##    The restarting 
##
##    
##
##
##
##
###########################################################################
version: '3.1'
services:

  restartr:
    image: heliumdatastage/restartr:0.0.1
    networks:
      - restartr-net
    ports:
      - 5552:5552
    depends_on:
      - mongo
    environment:
      MONGO_USERNAME: $MONGO_USERNAME
      MONGO_PASSWORD: $MONGO_USERNAME
      MONGO_PORT: 27017
      MONGO_HOST: mongo
      API_KEY: $API_KEY

  mongo:
    image: mongo:4.2
    networks:
      - restartr-net
    ports:
      - 27017:27017
    environment:
      MONGO_INITDB_ROOT_USERNAME: $MONGO_USERNAME
      MONGO_INITDB_ROOT_PASSWORD: $MONGO_PASSWORD

  mongo-express:
    image: mongo-express
    networks:
      - restartr-net
    ports:
      - 8081:8081
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: $MONGO_USERNAME
      ME_CONFIG_MONGODB_ADMINPASSWORD: $MONGO_PASSWORD

networks:
  restartr-net:
    driver: bridge

