apiVersion: v2
name: restartr
description: Helm chart for Restartr
type: application
# Chart Version
version: 0.1.0
# Using same version as the docker images at tranql/docker/bin/.ver
appVersion: 1.0
